const books = [
  {
    id: 1,
    title: "Sisi Tergelap Surga",
    author: "Brian Khrisna",
    category: "Fiksi",
    tag: "Bestseller 🔥",
    rating: 4.8,
    reviews: 142,
    originalPrice: "Rp99.000",
    price: "Rp79.000",
    image: "https://cdn.gramedia.com/uploads/picture_meta/2023/10/30/debsfyx6tcwnvbwdteeakv.jpg",
    description: "Kisah mengharukan tentang perjuangan dan realita kehidupan di sudut kota Jakarta.",
  },
  {
    id: 2,
    title: "How to Win Friends",
    author: "Dale Carnegie",
    category: "Pengembangan Diri",
    tag: "Wajib Baca ⭐",
    rating: 4.9,
    reviews: 530,
    originalPrice: "Rp175.000",
    price: "Rp149.000",
    image: "https://cdn.gramedia.com/uploads/picture_meta/2023/5/31/3dswgqvlfhavyeenh59ivk.jpg",
    description: "Panduan legendaris untuk membangun relasi, komunikasi persuasif, dan sukses karier.",
  },
  {
    id: 3,
    title: "Teka-Teki Gambar",
    author: "Studio Misteri",
    category: "Misteri",
    tag: "Terlaris 🧩",
    rating: 4.7,
    reviews: 98,
    originalPrice: "Rp229.000",
    price: "Rp199.000",
    image: "https://cdn.gramedia.com/uploads/product-metas/11zb4i2-ea.png",
    description: "Kumpulan misteri visual dan teka-teki logika mengasah otak dari gambar-gambar unik.",
  },
  {
    id: 4,
    title: "AI & Coding Masa Depan",
    author: "Tech Innovators",
    category: "Teknologi",
    tag: "Tren Baru 🚀",
    rating: 5.0,
    reviews: 215,
    originalPrice: "Rp160.000",
    price: "Rp129.000",
    image: "https://cdn.gramedia.com/uploads/product-metas/kxzgln-d2i.jpg",
    description: "Panduan komprehensif menguasai pemrograman modern dengan pemanfaatan Artificial Intelligence.",
  },
  {
    id: 5,
    title: "Seporsi Mie Ayam",
    author: "Rizky Santoso",
    category: "Inspirasi",
    tag: "Pilihan Editor 🍜",
    rating: 4.8,
    reviews: 87,
    originalPrice: "Rp169.000",
    price: "Rp149.000",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=500&q=80",
    description: "Refleksi kehidupan dan obrolan hangat penuh makna di balik semangkuk mie ayam jalanan.",
  },
  {
    id: 6,
    title: "Ronggeng Dukuh Paruk",
    author: "Ahmad Tohari",
    category: "Sastra & Budaya",
    tag: "Klasik 🏛️",
    rating: 4.9,
    reviews: 320,
    originalPrice: "Rp220.000",
    price: "Rp199.000",
    image: "https://cdn.gramedia.com/uploads/product-metas/uh0d0g8ukg.jpg",
    description: "Mahakarya sastra Indonesia tentang dinamika tradisi budaya dan perjalanan hidup Srintil.",
  },
  {
    id: 7,
    title: "Di Tanah Lada",
    author: "Ziggy Zezsyazeoviennazabrizkie",
    category: "Fiksi",
    tag: "Diskon 15% 🏷️",
    rating: 4.7,
    reviews: 164,
    originalPrice: "Rp145.000",
    price: "Rp120.000",
    image: "https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/products/a-d-i2ia-n.jpg",
    description: "Kisah kepolosan masa kecil yang berbaur dengan kepedihan hidup dan pencarian kebahagiaan.",
  },
  {
    id: 8,
    title: "Cantik Itu Luka",
    author: "Eka Kurniawan",
    category: "Fiksi",
    tag: "Edisi Spesial 📖",
    rating: 4.9,
    reviews: 470,
    originalPrice: "Rp160.000",
    price: "Rp135.000",
    image: "https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/items/9786020366517_Cantik-Itu-Luka-Hard-Cover---Limited-Edition.jpg",
    description: "Kisah epik keluarga Dewi Ayu yang menyatukan sejarah kolonial, dongeng rakyat, dan tragedi.",
  },
  {
    id: 9,
    title: "Sang Alkemis",
    author: "Paulo Coelho",
    category: "Pengembangan Diri",
    tag: "International Best 🌍",
    rating: 4.9,
    reviews: 610,
    originalPrice: "Rp115.000",
    price: "Rp99.000",
    image: "https://image.gramedia.net/rs:fit:0:0/plain/https://cdn.gramedia.com/uploads/items/9786020656069_Sang_Alkemis_cov.jpg",
    description: "Perjalanan spiritual anak gembala Andalusia dalam mengejar legenda pribadinya ke piramida Mesir.",
  }
];

export default books;